### ISSUE TITLE
Problems when we obtain certain details of organization

### ISSUE THREAD

**Issue by acosgaya** [ngzhian/pycrunchbase#18]
Hi!

I'm trying to obtain information of organization, and some failed.

Example of code:

from pycrunchbase import CrunchBase
cb = CrunchBase('API_KEY')
organization = cb.organization('ronaldm-morris')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-d79b71471e68> in <module>()
----> 1 organization = cb.organization('ronaldm-morris')

C:\Anaconda\lib\site-packages\pycrunchbase\pycrunchbase.pyc in organization(self, permalink)
     49         """
     50         node_data = self.get_node('organizations', permalink)
---> 51         return Organization(node_data) if node_data else None
     52 
     53     def person(self, permalink):

C:\Anaconda\lib\site-packages\pycrunchbase\resource\node.pyc in __init__(self, data)
     18         self.uuid = self.data.get('uuid')
     19         self._parse_properties()
---> 20         self._parse_relationship()
     21         self._coerce_values()
     22 

C:\Anaconda\lib\site-packages\pycrunchbase\resource\node.pyc in _parse_relationship(self)
     46             if rs_name in rs_dict:
     47                 setattr(
---> 48                     self, rs_name, Relationship(rs_name, rs_dict.get(rs_name)))
     49             else:
     50                 # fill in other relationships with None values

C:\Anaconda\lib\site-packages\pycrunchbase\resource\relationship.pyc in __init__(self, name, data)
     33             self.buildPage(name, data)
     34         elif self.cardinality in ['OneToOne']:
---> 35             self.buildPageItem(data.get('item'))
     36         else:
     37             self.buildPageItem(data)

C:\Anaconda\lib\site-packages\pycrunchbase\resource\relationship.pyc in buildPageItem(self, item)
     49         if not item or not hasattr(item, 'get'):
     50             return NonePageItemSingleton
---> 51         node = PageItem.build(item)
     52         self._node = node
     53         for prop in node.KNOWN_PROPERTIES:

C:\Anaconda\lib\site-packages\pycrunchbase\resource\pageitem.pyc in build(cls, data)
     30         if path == 'Ipo':
     31             from .ipo import IPO
---> 32             return IPO(data)
     33         if path == 'Organization' or path == 'OrganizationSummary':
     34             from .organization import Organization

C:\Anaconda\lib\site-packages\pycrunchbase\resource\node.pyc in __init__(self, data)
     18         self.uuid = self.data.get('uuid')
     19         self._parse_properties()
---> 20         self._parse_relationship()
     21         self._coerce_values()
     22 

C:\Anaconda\lib\site-packages\pycrunchbase\resource\node.pyc in _parse_relationship(self)
     46             if rs_name in rs_dict:
     47                 setattr(
---> 48                     self, rs_name, Relationship(rs_name, rs_dict.get(rs_name)))
     49             else:
     50                 # fill in other relationships with None values

C:\Anaconda\lib\site-packages\pycrunchbase\resource\relationship.pyc in __init__(self, name, data)
     35             self.buildPageItem(data.get('item'))
     36         else:
---> 37             self.buildPageItem(data)
     38 
     39     def buildPage(self, name, data):

C:\Anaconda\lib\site-packages\pycrunchbase\resource\relationship.pyc in buildPageItem(self, item)
     51         node = PageItem.build(item)
     52         self._node = node
---> 53         for prop in node.KNOWN_PROPERTIES:
     54             setattr(self, prop, getattr(node, prop))
     55         for prop in node.KNOWN_RELATIONSHIPS:

AttributeError: 'PageItem' object has no attribute 'KNOWN_PROPERTIES'

Thank you!

BR,

**Comment by ngzhian** [comment]
@acosgaya this should be fixed in the latest version (v0.3.2), please download it fom pypi https://pypi.python.org/pypi/pycrunchbase/. Thanks for the report!

**Comment by ppatel23** [comment]
I downloaded the latest version 0.3.5 (using pip install) and I still get the very same error - 

cb.organization('github')


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/pycrunchbase.py", line 51, in organization
    return Organization(node_data) if node_data else None
  File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/resource/node.py", line 20, in __init__
    self._parse_relationship()
  File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/resource/node.py", line 48, in _parse_relationship
    self, rs_name, Relationship(rs_name, rs_dict.get(rs_name)))
  File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/resource/relationship.py", line 35, in __init__
    self.buildPageItem(data.get('item'))
  File "/Users/Pinkesh/anaconda/lib/python2.7/site-packages/pycrunchbase/resource/relationship.py", line 60, in buildPageItem
    for prop in node.KNOWN_PROPERTIES:
AttributeError: 'PageItem' object has no attribute 'KNOWN_PROPERTIES'

**Comment by ngzhian** [comment]
@ppatel23 thanks for the report, this is fixed in v0.3.6. I hope this fix will make things more robust to any slight changes CrunchBase makes to their API.
I've personally tried `cb.organization('github')` and it works fine. Let me know if you encounter anymore issues.
Thank you once again!
